### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by hasanelfalakiy** [Ornstein89/ephemeris_generic_example#2]
Hi, I'm an astronomy lover and activist, I'm waiting for documentation on how to use this library.

**Comment by Ornstein89** [comment]
Hello, @hasanelfalakiy .

Thank you for your interest! This repo is not a library, it is an example of how to use external ephemeris libraries (C SPICE Toolkit and libephaccess) with CMake and C++. I created this repo basically for my students, who develop orbital modeling software, because sometimes it's not too clear how to use C SPICE Toolkit and libephaccess for beginners.

All required documentation is in readme.md and in comments inside the code already.

**Comment by hasanelfalakiy** [comment]
> Hello, @hasanelfalakiy .
> 
> Thank you for your interest! This repo is not a library, it is an example of how to use external ephemeris libraries (C SPICE Toolkit and libephaccess) with CMake and C++. I created this repo basically for my students, who develop orbital modeling software, because sometimes it's not too clear how to use C SPICE Toolkit and libephaccess for beginners.
> 
> All required documentation is in readme.md and in comments inside the code already.

oh nice, thanks bro 👍
